apiVersion: v1
kind: Service
metadata:
  name: dinmover-backend-service #The name of the Kubernetes Service to be created in the Kubernetes cluster
  namespace: dinmover-user-redis
spec:
  selector:
    app: dinmover-backend-app
  ports:
    - protocol: TCP
      port: 8000 #Service Port
      targetPort: 8000 #The port for the  application container
  type: NodePort
